/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlipCard {
        /**
          * Card Title - Required
         */
        "cardtitle": string;
        /**
          * Card Description - Required
         */
        "desc": string;
        /**
          * Card Image source - Required
         */
        "imgSrc": string;
    }
    interface MyAccordion {
        "color": string;
        "description": string;
        "label": string;
        "width": string;
    }
}
declare global {
    interface HTMLFlipCardElement extends Components.FlipCard, HTMLStencilElement {
    }
    var HTMLFlipCardElement: {
        prototype: HTMLFlipCardElement;
        new (): HTMLFlipCardElement;
    };
    interface HTMLMyAccordionElement extends Components.MyAccordion, HTMLStencilElement {
    }
    var HTMLMyAccordionElement: {
        prototype: HTMLMyAccordionElement;
        new (): HTMLMyAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "flip-card": HTMLFlipCardElement;
        "my-accordion": HTMLMyAccordionElement;
    }
}
declare namespace LocalJSX {
    interface FlipCard {
        /**
          * Card Title - Required
         */
        "cardtitle"?: string;
        /**
          * Card Description - Required
         */
        "desc"?: string;
        /**
          * Card Image source - Required
         */
        "imgSrc"?: string;
    }
    interface MyAccordion {
        "color"?: string;
        "description"?: string;
        "label"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "flip-card": FlipCard;
        "my-accordion": MyAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flip-card": LocalJSX.FlipCard & JSXBase.HTMLAttributes<HTMLFlipCardElement>;
            "my-accordion": LocalJSX.MyAccordion & JSXBase.HTMLAttributes<HTMLMyAccordionElement>;
        }
    }
}
